# Generated by Django 4.1 on 2022-08-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc_provider", "0025_user_field_codetoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="code",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="rsakey",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="token",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
